plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '1.17.3'
}

repositories {
    mavenCentral()
    google()
}

group 'anaribeiro.ist'
version '1.0.3.1'
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

intellij {
  version.set("2022.1.1")
  plugins.set(['java', 'android'])
  updateSinceUntilBuild.set(false)
}
